### PR TITLE
Added Ubuntu 20.04 and Bareos 20 signing key

### LINKED ISSUE #59: hardcoded key fingerprints break automatic key-rollout on debian/ubuntu
Hi,

https://github.com/voxpupuli/puppet-bareos/blob/master/manifests/repository.pp#L28

hardcodes pubkeys for bareos-repositories. This leads to:

Error: Could not set 'present' on ensure: The id in your manifest A0CFE15F71F798574AB363DD118283D9A7862C**EE** and the fingerprint from content/source don't match. Check for an error in the id and content/source is legitimate. (file: /etc/puppetlabs/code/environments/bareos/modules/apt/manifests/key.pp, line: 55)

Notice: /Stage[main]/Bareos::Repository/Apt::Source[bareos]/Apt::Key[Add key: A0CFE15F71F798574AB363DD118283D9A7862CEE from Apt::Source bareos]/Anchor[apt_key A0CFE15F71F798574AB363DD118283D9A7862CEE present]: Dependency Apt_key[Add key: A0CFE15F71F798574AB363DD118283D9A7862CEE from Apt::Source bareos] has failures: true
Warning: /Stage[main]/Bareos::Repository/Apt::Source[bareos]/Apt::Key[Add key: A0CFE15F71F798574AB363DD118283D9A7862CEE from Apt::Source bareos]/Anchor[apt_key A0CFE15F71F798574AB363DD118283D9A7862CEE present]: Skipping because of failed dependencies
Warning: /Stage[main]/Bareos::Repository/Apt::Source[bareos]/Apt::Setting[list-bareos]/File[/etc/apt/sources.list.d/bareos.list]: Skipping because of failed dependencies

That is because bareos signs each repo with it's own individual keys.

this is from ubuntu 18 with bareos latest (default).

pub   rsa4096 2019-12-11 [SC]
      641A 1497 F1B1 1BEA 945F  840F E5D8 82B2 8657 **AE28**
uid        [ unbekannt] Bareos 19.2 Signing Key <signing@bareos.com>

### PR DESCRIPTION
**Pull request by hugendudel**
#### Added Ubuntu 20.04 and Bareos 20 signing key
Hey folks,
- I have added Ubuntu 20.04 to the supported operating systems
- I have added the Bareos 20 release signing key

The logic with the key selection could be revised if necessary?

fixes [#85 #80]

### CODE REVIEW

**Comment by hugendudel** [comment]
Hi folks,

is there any news on this? Are you interested in the feature and would you like to have it? Are there any changes to be made?

I am looking forward to your feedback!

Greetings
Harm

**Comment by hugendudel** [comment]
Hi folks, any news on the changes or suggestions?

**Comment by root-expert** [comment]
Ubuntu 20.04 was never added to the metadata.json in this PR. @hugendudel are you interested in opening a new PR?

**Comment by hugendudel** [comment]
et voilà https://github.com/voxpupuli/puppet-bareos/pull/102

**Pull request merged**
