### PR TITLE
[BREAKING CHANGE] updated default version to Bareos 21

### LINKED ISSUE #80: Repo URL /latest/ is deprecated
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: all

## How to reproduce (e.g Puppet code you use)
```
class { 'bareos':
    repo_release          => '20',
}
```
http://download.bareos.org/bareos/release/

## What are you seeing
latest/ | 2020-04-16 16:47 | - | Bareos 19.2 (latest link is deprecated)

## What behaviour did you expect instead
Installing latest version of Bareos by default.

## Any additional information you'd like to impart
A default version pinning might be an option?
Which approach is preferred?

### PR DESCRIPTION
**Pull request by hugendudel**
#### Pull Request (PR) description
updated default version to Bareos 21

#### This Pull Request (PR) fixes the following issues
Fixes #80

### CODE REVIEW

**Comment by jhoblitt** [comment]
Rebased on current master.

**Comment by jhoblitt** [comment]
@hugendudel thank you for the contribution. The gha status seems to be stuck and I'm not a repo admin to override it.  I've rebased this branch on the current master as #115 and merged it.

**Comment by jhoblitt** [comment]
@hugendudel Are you using this mod to manage baseos 21? It looks like the removal of the `bareos-database-mysql` package would cause it to fail.

**Comment by hugendudel** [comment]
We use it with PostgreSQL, I will have a look at this issue tomorrow(UTC+1).

**Comment by hugendudel** [comment]
Ok, MySQL seems to be no longer supported. This information should be published somehow.
https://www.bareos.com/end-of-life-mysql/
And of course also remove the legacy.

**Comment by hugendudel** [comment]
MR is probably needed here, should we open an issue?

**Comment by jhoblitt** [comment]
@hugendudel I've put a kludge on the `acceptance` branch to remove the sqlite3/mysql packages. E.g. https://github.com/voxpupuli/puppet-bareos/pull/109/commits/68ddca32967813c343a6a694a08fa584eb42dd75

However, as a real "fix" I would like to delete the `db_driver` class parameter completely as the docs say this config file value is deprecated as well. I would prefer not to have to support sqlite3/mysql for baseos < 21. The question is is anyone is using this modules with sqlite3/mysql and bareos 19.2 or 20?

**Comment by hugendudel** [comment]
There's always someone using it, isn't it? But imho, one should read the release notes before updating?

**Comment by hugendudel** [comment]
Ok a suggestion, I'm not sure if a new version has been released since the change. But we could now build a release indicating this, and reset the default value for now?

**Comment by jhoblitt** [comment]
I had planned to make a 2.0.0 release of this mod (#121) but that was before I was aware of the baseos 21 compatibility issues.  We really need to get #109 sorted out.  I've opened https://github.com/voxpupuli/puppet-bareos/issues/125 as a live issue for this discussion. Can we shift this thread to the new issue?

**Pull request closed without merging**
